apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 107647632326.dkr.ecr.us-east-2.amazonaws.com/test-node
  newName: 107647632326.dkr.ecr.us-east-2.amazonaws.com/test-node
  newTag: fbf317b3d31fe6cfd29ed9d744483284c2900386
- name: ghcr.io/wlgns5376/example-app
  newTag: dev
resources:
- ../../base
