apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-argo
  labels:
    app: test-argo
spec:
  type: RollingUpdate
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  replicas: 3
  selector:
    matchLabels:
      app: test-argo
  template:
    metadata:
      labels:
        app: ${{ secrets.ECR_REGI }}
    spec:
      containers:
      - name: 
        image: sd0241/ssacnode:0.3
        ports:
        - containerPort: 8080 #상의
