apiVersion: v1
kind: Service
metadata:
  name: <name>
spec:
  type: LoadBalancer
  selector:
    app: <NAME>
  ports:
    - protocol: TCP
      port: 80 # 이부분을 443으로 해야하나?
      targetPort: 8080 # 상의
