apiVersion: v1
kind: Service
metadata:
  name: test-argo
  labels:
    app: test-argo
spec:
  type: LoadBalancer
  selector:
    app: test-argo
  ports:
    - protocol: TCP
      port: 80 # 이부분을 443으로 해야하나?
      targetPort: 8080 # 상의
