---
apiVersion: v1
kind: Service
metadata:
  name: ssac-front
  labels:
    app: ssac-front
    tier: front
spec:
  type: NodePort # 서비스 타입
  ports:
    - port: 3000 # 서비스 포트
      targetPort: 3000 # 타켓, 즉 pod의 포트
      protocol: TCP
  selector:
    app: ssac-front
​
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingttti
  annotations:
    #kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: instance
    #alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: log-land.com
    external-dns.alpha.kubernetes.io/ttl: "100"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:107647632326:certificate/dc59a277-4a13-45b8-b989-995e0ede6a37
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  tls:
    - hosts:
        - log-land.com
  ingressClassName: alb
  defaultBackend:
    service:
      name: ssac-front
      port:
        number: 3000
  rules:
    - host: log-land.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssac-front
                port:
                  number: 3000
          # - path: /auth
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: ssac-front
          #       port:
          #         number: 3000
---
