apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssac-back
  labels:
    app: ssac-back
spec:

  replicas: 2
  selector:
    matchLabels:
      app: ssac-back
      tier: back
  template:
    metadata:
      labels:
        app: ssac-back
        tier: back
    spec:
      containers:
        - name: ssac-back
          image: 107647632326.dkr.ecr.us-east-2.amazonaws.com/ssac-back:4
          resources:
            limits:
              cpu: "200m"
              memory: 128Mi
            requests:
              cpu: "100m"
              memory: 64Mi
          ports:
            - containerPort: 5000
